services:
  - type: web
    name: my-react-app
    env: static
    buildCommand: npm run build
    startCommand: npm start
    staticPublishPath: /build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
